const MenuItem = require("../models/MenuItem");

const menuSeedData = [
  {
    name: "BELUGA CAVIAR",
    category: "Breakfast",
    subcategory: "Raw Bar",
    description: "30g imperial caviar, blinis, creme fraiche, chives",
    price: 185,
    available: true,
  },
  {
    name: "OYSTERS ROYALE",
    category: "Breakfast",
    subcategory: "Raw Bar",
    description: "Gillardeau oysters, champagne mignonette, gold leaf",
    price: 28,
    available: true,
  },
  {
    name: "TUNA TARTARE",
    category: "Breakfast",
    subcategory: "Raw Bar",
    description: "Bluefin tuna, Ossetra caviar, avocado, yuzu",
    price: 42,
    available: true,
  },
  {
    name: "KING CRAB COCKTAIL",
    category: "Breakfast",
    subcategory: "Raw Bar",
    description: "Alaskan king crab, citrus aioli, microgreens",
    price: 38,
    available: true,
  },
  {
    name: "LOBSTER BENEDICT",
    category: "Breakfast",
    subcategory: "Morning Plates",
    description: "Maine lobster, truffle hollandaise, brioche, caviar",
    price: 48,
    available: true,
  },
  {
    name: "CRAB CAKE ROYALE",
    category: "Breakfast",
    subcategory: "Morning Plates",
    description: "Jumbo lump crab, black truffle, aged Gruyere, chives",
    price: 52,
    available: true,
  },
  {
    name: "SMOKED SALMON ROYALE",
    category: "Breakfast",
    subcategory: "Morning Plates",
    description: "Scottish salmon, soft scrambled eggs, Ossetra caviar",
    price: 45,
    available: true,
  },
  {
    name: "SCALLOPS & TRUFFLE",
    category: "Breakfast",
    subcategory: "Morning Plates",
    description: "Seared scallops, black truffle, brioche, lemon butter",
    price: 58,
    available: true,
  },
  {
    name: "LOBSTER THERMIDOR ROLL",
    category: "Lunch",
    subcategory: "Sandwiches & Rolls",
    description: "Maine lobster, cream sauce, truffle butter, brioche",
    price: 58,
    available: true,
  },
  {
    name: "TUNA TATAKI SANDWICH",
    category: "Lunch",
    subcategory: "Sandwiches & Rolls",
    description: "Seared bluefin tuna, wasabi aioli, cucumber, sesame",
    price: 48,
    available: true,
  },
  {
    name: "KING CRAB CLUB",
    category: "Lunch",
    subcategory: "Sandwiches & Rolls",
    description: "Alaskan king crab, avocado, heirloom tomato, caviar mayo",
    price: 52,
    available: true,
  },
  {
    name: "TRUFFLE SALMON",
    category: "Lunch",
    subcategory: "Sandwiches & Rolls",
    description: "Scottish salmon, black truffle, aged Comte, arugula",
    price: 42,
    available: true,
  },
  {
    name: "BLUEFIN TUNA BOWL",
    category: "Lunch",
    subcategory: "Bowls & Salads",
    description: "Sashimi-grade bluefin, sushi rice, Ossetra caviar, wasabi",
    price: 62,
    available: true,
  },
  {
    name: "LOBSTER CAESAR",
    category: "Lunch",
    subcategory: "Bowls & Salads",
    description: "Maine lobster, baby romaine, parmesan crisp, anchovy",
    price: 48,
    available: true,
  },
  {
    name: "TRUFFLE BURRATA",
    category: "Lunch",
    subcategory: "Bowls & Salads",
    description: "Italian burrata, black truffle, heirloom tomatoes, basil oil",
    price: 38,
    available: true,
  },
  {
    name: "SEAFOOD BISQUE",
    category: "Lunch",
    subcategory: "Bowls & Salads",
    description: "Lobster, crab, cognac, creme fraiche, chives",
    price: 28,
    available: true,
  },
  {
    name: "DOVER SOLE MEUNIERE",
    category: "Dinner",
    subcategory: "From the Ocean",
    description: "Whole Dover sole, brown butter, capers, lemon, parsley",
    price: 88,
    available: true,
  },
  {
    name: "LOBSTER THERMIDOR",
    category: "Dinner",
    subcategory: "From the Ocean",
    description: "Whole Maine lobster, cognac cream, Gruyere, truffle",
    price: 125,
    available: true,
  },
  {
    name: "TURBOT ROYALE",
    category: "Dinner",
    subcategory: "From the Ocean",
    description: "Wild turbot, champagne beurre blanc, caviar, asparagus",
    price: 95,
    available: true,
  },
  {
    name: "WILD SALMON EN CROUTE",
    category: "Dinner",
    subcategory: "From the Ocean",
    description: "Scottish salmon, spinach, mushroom duxelles, puff pastry",
    price: 78,
    available: true,
  },
  {
    name: "BRANZINO AL SALE",
    category: "Dinner",
    subcategory: "From the Ocean",
    description: "Whole sea bass, sea salt crust, herbs, lemon oil",
    price: 82,
    available: true,
  },
  {
    name: "KING CRAB OSCAR",
    category: "Dinner",
    subcategory: "Shellfish & Specialties",
    description: "Alaskan king crab, asparagus, bearnaise, Ossetra caviar",
    price: 145,
    available: true,
  },
  {
    name: "BOUILLABAISSE ROYALE",
    category: "Dinner",
    subcategory: "Shellfish & Specialties",
    description: "Lobster, langoustines, scallops, saffron broth, rouille",
    price: 98,
    available: true,
  },
  {
    name: "DIVER SCALLOPS",
    category: "Dinner",
    subcategory: "Shellfish & Specialties",
    description: "Hokkaido scallops, cauliflower puree, black truffle, caviar",
    price: 85,
    available: true,
  },
  {
    name: "LOBSTER RISOTTO",
    category: "Dinner",
    subcategory: "Shellfish & Specialties",
    description: "Maine lobster, carnaroli rice, white truffle, parmesan",
    price: 92,
    available: true,
  },
  {
    name: "PLATEAU DE FRUITS DE MER",
    category: "Dinner",
    subcategory: "Shellfish & Specialties",
    description: "Oysters, lobster, king crab, langoustines, caviar",
    price: 285,
    available: true,
  },
  {
    name: "PERRIER-JOUET",
    category: "Drinks",
    subcategory: "Sparkling & Premium Waters",
    description: "Non-alcoholic sparkling, elderflower, French bubbles",
    price: 28,
    available: true,
  },
  {
    name: "VOSS ARTESIAN WATER",
    category: "Drinks",
    subcategory: "Sparkling & Premium Waters",
    description: "Norwegian artesian water, still or sparkling",
    price: 18,
    available: true,
  },
  {
    name: "ACQUA PANNA",
    category: "Drinks",
    subcategory: "Sparkling & Premium Waters",
    description: "Italian natural spring water, Tuscany",
    price: 15,
    available: true,
  },
  {
    name: "SAN PELLEGRINO",
    category: "Drinks",
    subcategory: "Sparkling & Premium Waters",
    description: "Italian sparkling mineral water, glass bottle",
    price: 15,
    available: true,
  },
  {
    name: "GOLDEN ELIXIR",
    category: "Drinks",
    subcategory: "Signature Mocktails",
    description: "Saffron, honey, rose water, sparkling water, gold leaf",
    price: 22,
    available: true,
  },
  {
    name: "TRUFFLE TONIC",
    category: "Drinks",
    subcategory: "Signature Mocktails",
    description: "Truffle essence, tonic water, cucumber, thyme",
    price: 18,
    available: true,
  },
  {
    name: "CAVIAR COOLER",
    category: "Drinks",
    subcategory: "Signature Mocktails",
    description: "Cucumber, lime, mint, elderflower, sparkling water",
    price: 20,
    available: true,
  },
  {
    name: "ROYAL REFRESHER",
    category: "Drinks",
    subcategory: "Signature Mocktails",
    description: "Pomegranate, rose, cardamom, sparkling water",
    price: 18,
    available: true,
  },
  {
    name: "VIRGIN BELLINI",
    category: "Drinks",
    subcategory: "Signature Mocktails",
    description: "White peach puree, sparkling grape juice, mint",
    price: 16,
    available: true,
  },
  {
    name: "ESPRESSO ROYALE",
    category: "Drinks",
    subcategory: "Signature Mocktails",
    description: "Double espresso, vanilla, cream, cinnamon",
    price: 14,
    available: true,
  },
];

const seedMenu = async () => {
  const existingCount = await MenuItem.countDocuments();
  if (existingCount > 0) {
    return;
  }

  await MenuItem.insertMany(menuSeedData);
  // eslint-disable-next-line no-console
  console.log("Seeded menu items");
};

module.exports = seedMenu;
